- hosts: localhost
  gather_facts: no
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - before

- hosts: EC
  gather_facts: no
  become: true
  vars_files:
    - vars/common.yml
    - vars/{{group_names[1]}}.yml
  roles:
    - transfer
    - firewall
    - java
    - net-snmp
    - rsyslog
    - chrony
    - dhcp
    - tftp
    - httpd
    - { role: pacemaker, when: "ha_flag"}
    - sar
    - expect
    - bc
    - ec
    - { role: ra-ec, when: "ha_flag"}

- hosts: DB
  gather_facts: no
  become: true
  vars_files:
    - vars/common.yml
    - vars/{{group_names[1]}}.yml
  roles:
    - transfer
    - { role: postgre, when: "install_flag"}
    - db-ec
    - firewall

- hosts: localhost
  gather_facts: no
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - after

