# Setting net-snmp
  - include: getrpm.yml
    when: download_flag
  - name: net-snmp install 1
    shell: rpm -Uvh --replacepkgs {{ rpm_path }}/{{ folder_name }}/glibc-common-2.17-105.el7.x86_64.rpm
  - name: net-snmp install 2
    shell: rpm -Uvh --replacepkgs {{ rpm_path }}/{{ folder_name }}/glibc-2.17-105.el7.x86_64.rpm
  - name: net-snmp install 3
    shell: rpm -Uvh --replacepkgs {{ rpm_path }}/{{ folder_name }}/perl-*
  - name: net-snmp install 4
    shell: rpm -Uvh --replacepkgs {{ rpm_path }}/{{ folder_name }}/openssl098e-0.9.8e-29.el7.centos.3.x86_64.rpm
  - name: net-snmp install 5
    shell: rpm -Uvh --replacepkgs {{ rpm_path }}/{{ folder_name }}/net-snmp-libs-5.7.2-24.el7_2.1.x86_64.rpm
  - name: net-snmp install 6
    shell: rpm -Uvh --replacepkgs {{ rpm_path }}/{{ folder_name }}/lm_sensors-libs-3.3.4-11.el7.x86_64.rpm
  - name: net-snmp install 7
    shell: rpm -Uvh --replacepkgs {{ rpm_path }}/{{ folder_name }}/net-snmp-agent-libs-5.7.2-24.el7_2.1.x86_64.rpm
  - name: net-snmp install 8
    shell: rpm -Uvh --replacepkgs {{ rpm_path }}/{{ folder_name }}/net-snmp-5.7.2-24.el7_2.1.x86_64.rpm
  - name: replace net-snmp setting
    replace: dest=/usr/lib/systemd/system/snmptrapd.service regexp='ExecStart=/usr/sbin/snmptrapd \$OPTIONS -f' replace='ExecStart=/usr/sbin/snmptrapd -On $OPTIONS -f'
