# Getting ec script
  - name: wget jar
    shell: wget --no-check-certificate --no-cookies {{ item.url }} -O {{ ec_path }}/{{ folder_name_bin }}/{{ item.file_name }}
    with_items:
      - "{{ script_list }}"



    
