# Getting ec conf
  - name: wget jar
    shell: wget --no-check-certificate --no-cookies {{ item.url }} -O {{ ec_path }}/{{ folder_name_conf }}/{{ item.file_name }}
    with_items:
      - "{{ conf_list }}"



    
