# Getting ec jar
  - name: wget src
    shell: wget --no-check-certificate --no-cookies {{ item.url }} -O {{ rpm_path }}/{{ item.file_name }}
    with_items:
      - "{{ src_list }}"
    when: download_flag
  - shell: tar zxvf {{ rpm_path }}/master.tar.gz -C {{ rpm_path }}
    when: download_flag
  - shell: cp -r {{ rpm_path }}/element-controller-master/EcMainModule/src/msf {{ ec_path }}
    when: download_flag
  - shell: cp {{ rpm_path }}/element-controller-master/jar_create.sh  {{ ec_path }}
    when: download_flag
  - shell: cp -r {{ installing_ec_path }}/msf {{ ec_path }}
    when: download_flag == false
  - shell: cp {{ installing_ec_path }}/jar_create.sh {{ ec_path }}
    when: download_flag == false
  - name: make jar
    shell: sh jar_create.sh
    args:
      chdir: "{{ ec_path }}/"
  - name: mv jar
    shell: mv {{ ec_path }}/{{ ec_jar_name }} {{ ec_path }}/lib
